CREATE TABLE IF NOT EXISTS endpoint_hit (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app varchar(255),
  uri varchar(255),
  ip varchar(255),
  datetime timestamp without time zone
);